default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres


development:
  <<: *default
  database: weather_hotwires_development

test:
  <<: *default
  database: weather_hotwires_test

production:
  <<: *default
  database: weather_hotwires_production
  username: weather_hotwires
  password: <%= ENV["WEATHER_HOTWIRES_DATABASE_PASSWORD"] %>
